/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie la santé du BFF */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check_apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie la connexion avec l'API Core et Calendar (Rust) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connexion réussie */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckApiResponse"];
                    };
                };
                /** @description API Core injoignable */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Charge les données initiales du calendrier
         * @description Charge en une fois les événements de la période, les personnes assignables, les catégories et l'utilisateur courant
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Données bootstrap chargées avec succès */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarBootstrapResponse"];
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupère les événements sur une plage de dates
         * @description Charge les événements utiles à la vue mois/semaine/jour
         */
        get: {
            parameters: {
                query: {
                    /** @description Date de début au format YYYY-MM-DD */
                    from: string;
                    /** @description Date de fin au format YYYY-MM-DD */
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des événements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarEvent"][];
                    };
                };
                /** @description Paramètres invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Crée un nouvel événement
         * @description Crée un événement calendrier et retourne l'objet enrichi avec son ID serveur
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCalendarEventBody"];
                };
            };
            responses: {
                /** @description Événement créé avec succès */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateCalendarEventBody"];
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Supprime un événement
         * @description Supprime un événement identifié par son ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identifiant unique de l'événement */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Événement supprimé avec succès */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Événement non trouvé */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Modifie un événement existant
         * @description Met à jour un événement identifié par son ID
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identifiant unique de l'événement */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CalendarEvent"];
                };
            };
            responses: {
                /** @description Événement modifié avec succès */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarEvent"];
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Événement non trouvé */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/calendar/events/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Met à jour le statut d’approbation d’un événement
         * @description Valide, refuse ou remet en attente un événement identifié par son ID
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Identifiant unique de l'événement */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCalendarEventApprovalBody"];
                };
            };
            responses: {
                /** @description Statut d’approbation mis à jour */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarEvent"];
                    };
                };
                /** @description Données invalides */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Événement non trouvé */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/calendar/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupère le référentiel des personnes assignables
         * @description Charge la liste complète des personnes pouvant être assignées à un événement
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des personnes assignables */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarAssignee"][];
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupère le référentiel des catégories
         * @description Charge la liste des catégories d'événements disponibles
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des catégories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarCategory"][];
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Récupère le référentiel des services calendrier
         * @description Charge la liste des services municipaux utilisables pour qualifier les événements
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste des services calendrier */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarService"][];
                    };
                };
                /** @description Erreur serveur */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CalendarRecurrence: {
            /**
             * @description Fréquence de récurrence
             * @enum {string}
             */
            frequency: "none" | "daily" | "weekly" | "monthly";
            /** @description Intervalle de récurrence (par défaut 1) */
            interval?: number;
            /** @description Jours de la semaine (0=dimanche, 6=samedi). Utilisé pour les récurrences hebdomadaires */
            daysOfWeek?: number[];
            /** @description Date de fin inclusive (format YYYY-MM-DD) */
            endsOn?: string;
        };
        CalendarAssignee: {
            /** @description Identifiant unique de la personne */
            id: string | number;
            /** @description Nom complet affichable */
            name: string;
            /**
             * Format: email
             * @description Adresse email
             */
            email?: string;
            /** @description Fonction ou rôle métier */
            role?: string;
            /**
             * Format: uri
             * @description URL de l'image de profil
             */
            avatarUrl?: string;
        };
        CalendarEvent: {
            /** @description Identifiant stable. Optionnel en création, obligatoire en lecture. */
            id?: string | number;
            /** @description Titre de l'événement */
            title: string;
            /** @description Date de début (format YYYY-MM-DD ou DD-MM-YYYY) */
            date: string;
            /** @description Date de fin pour les événements multi-jours (format YYYY-MM-DD ou DD-MM-YYYY) */
            endDate?: string;
            /**
             * @description Catégorie: meeting (Réunion), activity (Animation), ceremony (Cérémonie), other (Autre)
             * @enum {string}
             */
            category?: "meeting" | "activity" | "ceremony" | "other";
            /** @description Service ou département organisateur */
            service?: string;
            /** @description Heure de début au format HH:mm */
            startTime?: string;
            /** @description Heure de fin au format HH:mm */
            endTime?: string;
            /** @description Lieu de l'événement */
            location?: string;
            /** @description Description détaillée */
            description?: string;
            /** @description Liste des identifiants des personnes assignées */
            assigneeIds?: (string | number)[];
            /** @description Objets complets des personnes assignées (optionnel, peut être reconstruit côté front) */
            assignees?: components["schemas"]["CalendarAssignee"][];
            recurrence?: components["schemas"]["CalendarRecurrence"] & unknown;
            /**
             * @description Statut d'approbation de l'événement
             * @enum {string}
             */
            approvalStatus?: "pending" | "approved" | "rejected";
            /** @description Identifiant de l'utilisateur ayant créé l'événement */
            createdById?: string | number;
            /** @description Indique si l’utilisateur courant peut valider ou refuser cet événement */
            canValidate?: boolean;
            /** @description Indique si l’utilisateur courant peut modifier cet événement */
            canEdit?: boolean;
            /** @description Indique si l’utilisateur courant peut supprimer cet événement */
            canDelete?: boolean;
            /** @description Liste des rôles pouvant voir l'événement */
            visibleToRoles?: ("user" | "responsable" | "mayor")[];
        };
        CalendarCategory: {
            /** @description Libellé affiché (ex: Réunion) */
            label: string;
            /** @description Valeur interne (ex: meeting) */
            value: string;
        };
        CalendarService: {
            /** @description Libellé affiché (ex: Direction générale) */
            label: string;
            /** @description Valeur interne (ex: direction) */
            value: string;
        };
        CalendarBootstrapResponse: {
            /** @description Liste des événements de la période */
            events: components["schemas"]["CalendarEvent"][];
            /** @description Référentiel des personnes assignables */
            assignees: components["schemas"]["CalendarAssignee"][];
            /** @description Référentiel des catégories */
            categories: components["schemas"]["CalendarCategory"][];
            /** @description Référentiel des services calendrier */
            services: components["schemas"]["CalendarService"][];
            /** @description Utilisateur actuellement authentifié (optionnel) */
            currentUser?: {
                id: string | number;
                name: string;
                /** Format: email */
                email: string;
                role?: string;
                groupIds: number[];
            };
            /**
             * @description Périmètre du référentiel des personnes assignables
             * @enum {string}
             */
            assigneeScope?: "all" | "groups" | "self";
        };
        CalendarStatistics: {
            /** @description Nombre d'événements ce mois */
            monthCount: number;
            /** @description Nombre d'événements cette semaine */
            weekCount: number;
            /** @description Nombre d'événements aujourd'hui */
            todayCount: number;
        };
        CalendarEventParams: {
            /**
             * @description Identifiant de l'événement
             * @example 123
             */
            eventId: string | number;
        };
        CalendarEventsQuery: {
            /** @description Date de début (YYYY-MM-DD) */
            startDate?: string;
            /** @description Date de fin (YYYY-MM-DD) */
            endDate?: string;
            /** @description Filtre sur une personne assignée */
            assigneeId?: string;
            /** @description Filtre sur une catégorie */
            category?: string;
        };
        CreateCalendarEventBody: {
            /** @description Titre de l'événement */
            title: string;
            /** @description Date de début (format YYYY-MM-DD ou DD-MM-YYYY) */
            date: string;
            /** @description Date de fin pour les événements multi-jours (format YYYY-MM-DD ou DD-MM-YYYY) */
            endDate?: string;
            /**
             * @description Catégorie: meeting (Réunion), activity (Animation), ceremony (Cérémonie), other (Autre)
             * @enum {string}
             */
            category?: "meeting" | "activity" | "ceremony" | "other";
            /** @description Service ou département organisateur */
            service?: string;
            /** @description Heure de début au format HH:mm */
            startTime?: string;
            /** @description Heure de fin au format HH:mm */
            endTime?: string;
            /** @description Lieu de l'événement */
            location?: string;
            /** @description Description détaillée */
            description?: string;
            /** @description Liste des identifiants des personnes assignées */
            assigneeIds?: (string | number)[];
            /** @description Objets complets des personnes assignées (optionnel, peut être reconstruit côté front) */
            assignees?: components["schemas"]["CalendarAssignee"][];
            recurrence?: components["schemas"]["CalendarRecurrence"] & unknown;
            /**
             * @description Statut d'approbation de l'événement
             * @enum {string}
             */
            approvalStatus?: "pending" | "approved" | "rejected";
            /** @description Identifiant de l'utilisateur ayant créé l'événement */
            createdById?: string | number;
            /** @description Indique si l’utilisateur courant peut valider ou refuser cet événement */
            canValidate?: boolean;
            /** @description Indique si l’utilisateur courant peut modifier cet événement */
            canEdit?: boolean;
            /** @description Indique si l’utilisateur courant peut supprimer cet événement */
            canDelete?: boolean;
            /** @description Liste des rôles pouvant voir l'événement */
            visibleToRoles?: ("user" | "responsable" | "mayor")[];
        };
        UpdateCalendarEventBody: {
            /** @description Titre de l'événement */
            title?: string;
            /** @description Date de début (format YYYY-MM-DD ou DD-MM-YYYY) */
            date?: string;
            /** @description Date de fin pour les événements multi-jours (format YYYY-MM-DD ou DD-MM-YYYY) */
            endDate?: string;
            /**
             * @description Catégorie: meeting (Réunion), activity (Animation), ceremony (Cérémonie), other (Autre)
             * @enum {string}
             */
            category?: "meeting" | "activity" | "ceremony" | "other";
            /** @description Service ou département organisateur */
            service?: string;
            /** @description Heure de début au format HH:mm */
            startTime?: string;
            /** @description Heure de fin au format HH:mm */
            endTime?: string;
            /** @description Lieu de l'événement */
            location?: string;
            /** @description Description détaillée */
            description?: string;
            /** @description Liste des identifiants des personnes assignées */
            assigneeIds?: (string | number)[];
            /** @description Objets complets des personnes assignées (optionnel, peut être reconstruit côté front) */
            assignees?: components["schemas"]["CalendarAssignee"][];
            recurrence?: components["schemas"]["CalendarRecurrence"] & unknown;
            /**
             * @description Statut d'approbation de l'événement
             * @enum {string}
             */
            approvalStatus?: "pending" | "approved" | "rejected";
            /** @description Identifiant de l'utilisateur ayant créé l'événement */
            createdById?: string | number;
            /** @description Indique si l’utilisateur courant peut valider ou refuser cet événement */
            canValidate?: boolean;
            /** @description Indique si l’utilisateur courant peut modifier cet événement */
            canEdit?: boolean;
            /** @description Indique si l’utilisateur courant peut supprimer cet événement */
            canDelete?: boolean;
            /** @description Liste des rôles pouvant voir l'événement */
            visibleToRoles?: ("user" | "responsable" | "mayor")[];
        };
        UpdateCalendarEventApprovalBody: {
            /**
             * @description Nouveau statut d'approbation de l'événement
             * @enum {string}
             */
            approvalStatus: "pending" | "approved" | "rejected";
        };
        ApiError: {
            code: string;
            message: string;
            details?: unknown;
        };
        CheckApiResponse: {
            /** @example OK */
            status: string;
            /** @example Connected */
            core_api: string;
            /** @example Connected */
            calendar_api: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
